services:
    rs_di_extra.definition_converter:
        class:         RS\DiExtraBundle\Converter\DefinitionConverter
        calls:
            -
                method:       inject
                arguments:
                    -          '@annotation_reader'
                    -          '%kernel.environment%'
                    -          '%kernel.cache_dir%'

#    rs_di_extra.controller_resolver:
#        decorates:     controller_resolver
#        class:         RS\DiExtraBundle\HttpKernel\ControllerResolver
#        arguments:
#            -          '@rs_di_extra.controller_resolver.inner'
#    rs_di_extra.argument_resolver_parameter_value_resolver:
#        public:        false
#        class:         RS\DiExtraBundle\HttpKernel\Controller\ArgumentResolver\ParameterValueResolver
#        tags:
#            -          'controller.argument_value_resolver'
#        arguments:
#            -          null
#            -          '@service_container'

