services:
    rs_di_extra.definition_converter:
        class:         RS\DiExtraBundle\Converter\DefinitionConverter
        calls:
            -
                method:       inject
                arguments:
                    -          '%kernel.environment%'
                    -          '%kernel.cache_dir%'
